# Specify the base image
FROM php:7.4-apache

RUN sed -i 's/DirectoryIndex.*/DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm/g' "/etc/apache2/mods-enabled/dir.conf"

RUN docker-php-ext-install mysqli

# Copy the application files to the container
ADD bootcamp-devops-2023/app-295devops-travel /var/www/html/



